namespace JRDEVData.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddRequiredToUserForeignKeys : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Applications", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Companies", "CompanyAdminId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Messages", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Messages", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Companies", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Companies", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Messages", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Notes", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Notes", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Notes", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Jobs", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Resumes", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Resumes", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Resumes", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.SavedJobs", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.SavedJobs", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.SavedJobs", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.UserSkills", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Clicks", "ClickerId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Clicks", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Clicks", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.JobTimeStamps", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.JobTimeStamps", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.JobTimeStamps", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Jobs", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Jobs", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Applications", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Applications", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.TalentProfiles", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.TalentProfiles", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.TalentProfiles", "UserUpdatedId", "dbo.AspNetUsers");
            DropIndex("dbo.Applications", new[] { "UserId" });
            DropIndex("dbo.Companies", new[] { "CompanyAdminId" });
            DropIndex("dbo.Messages", new[] { "UserCreatedId" });
            DropIndex("dbo.Messages", new[] { "UserUpdatedId" });
            DropIndex("dbo.Companies", new[] { "UserCreatedId" });
            DropIndex("dbo.Companies", new[] { "UserUpdatedId" });
            DropIndex("dbo.Messages", new[] { "UserId" });
            DropIndex("dbo.Notes", new[] { "UserCreatedId" });
            DropIndex("dbo.Notes", new[] { "UserUpdatedId" });
            DropIndex("dbo.Notes", new[] { "UserId" });
            DropIndex("dbo.Jobs", new[] { "UserId" });
            DropIndex("dbo.Resumes", new[] { "UserCreatedId" });
            DropIndex("dbo.Resumes", new[] { "UserUpdatedId" });
            DropIndex("dbo.Resumes", new[] { "UserId" });
            DropIndex("dbo.SavedJobs", new[] { "UserCreatedId" });
            DropIndex("dbo.SavedJobs", new[] { "UserUpdatedId" });
            DropIndex("dbo.SavedJobs", new[] { "UserId" });
            DropIndex("dbo.UserSkills", new[] { "UserId" });
            DropIndex("dbo.Clicks", new[] { "ClickerId" });
            DropIndex("dbo.Clicks", new[] { "UserCreatedId" });
            DropIndex("dbo.Clicks", new[] { "UserUpdatedId" });
            DropIndex("dbo.JobTimeStamps", new[] { "UserId" });
            DropIndex("dbo.JobTimeStamps", new[] { "UserCreatedId" });
            DropIndex("dbo.JobTimeStamps", new[] { "UserUpdatedId" });
            DropIndex("dbo.Jobs", new[] { "UserCreatedId" });
            DropIndex("dbo.Jobs", new[] { "UserUpdatedId" });
            DropIndex("dbo.Applications", new[] { "UserCreatedId" });
            DropIndex("dbo.Applications", new[] { "UserUpdatedId" });
            DropIndex("dbo.TalentProfiles", new[] { "UserId" });
            DropIndex("dbo.TalentProfiles", new[] { "UserCreatedId" });
            DropIndex("dbo.TalentProfiles", new[] { "UserUpdatedId" });
            AlterColumn("dbo.Applications", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Applications", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Applications", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Jobs", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Jobs", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Jobs", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Clicks", "ClickerId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Clicks", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Clicks", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Companies", "CompanyAdminId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Companies", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Companies", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Messages", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Messages", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Messages", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Notes", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Notes", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Notes", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Resumes", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Resumes", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Resumes", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SavedJobs", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SavedJobs", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.SavedJobs", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserSkills", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.JobTimeStamps", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.JobTimeStamps", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.JobTimeStamps", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TalentProfiles", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TalentProfiles", "UserCreatedId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.TalentProfiles", "UserUpdatedId", c => c.String(nullable: false, maxLength: 128));
            CreateIndex("dbo.Applications", "UserId");
            CreateIndex("dbo.Companies", "CompanyAdminId");
            CreateIndex("dbo.Messages", "UserCreatedId");
            CreateIndex("dbo.Messages", "UserUpdatedId");
            CreateIndex("dbo.Companies", "UserCreatedId");
            CreateIndex("dbo.Companies", "UserUpdatedId");
            CreateIndex("dbo.Messages", "UserId");
            CreateIndex("dbo.Notes", "UserCreatedId");
            CreateIndex("dbo.Notes", "UserUpdatedId");
            CreateIndex("dbo.Notes", "UserId");
            CreateIndex("dbo.Jobs", "UserId");
            CreateIndex("dbo.Resumes", "UserCreatedId");
            CreateIndex("dbo.Resumes", "UserUpdatedId");
            CreateIndex("dbo.Resumes", "UserId");
            CreateIndex("dbo.SavedJobs", "UserCreatedId");
            CreateIndex("dbo.SavedJobs", "UserUpdatedId");
            CreateIndex("dbo.SavedJobs", "UserId");
            CreateIndex("dbo.UserSkills", "UserId");
            CreateIndex("dbo.Clicks", "ClickerId");
            CreateIndex("dbo.Clicks", "UserCreatedId");
            CreateIndex("dbo.Clicks", "UserUpdatedId");
            CreateIndex("dbo.JobTimeStamps", "UserId");
            CreateIndex("dbo.JobTimeStamps", "UserCreatedId");
            CreateIndex("dbo.JobTimeStamps", "UserUpdatedId");
            CreateIndex("dbo.Jobs", "UserCreatedId");
            CreateIndex("dbo.Jobs", "UserUpdatedId");
            CreateIndex("dbo.Applications", "UserCreatedId");
            CreateIndex("dbo.Applications", "UserUpdatedId");
            CreateIndex("dbo.TalentProfiles", "UserId");
            CreateIndex("dbo.TalentProfiles", "UserCreatedId");
            CreateIndex("dbo.TalentProfiles", "UserUpdatedId");
            AddForeignKey("dbo.Applications", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Companies", "CompanyAdminId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Messages", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Messages", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Companies", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Companies", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Messages", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Notes", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Notes", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Notes", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Jobs", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Resumes", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Resumes", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Resumes", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.SavedJobs", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.SavedJobs", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.SavedJobs", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.UserSkills", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Clicks", "ClickerId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Clicks", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Clicks", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.JobTimeStamps", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.JobTimeStamps", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.JobTimeStamps", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Jobs", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Jobs", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Applications", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Applications", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.TalentProfiles", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.TalentProfiles", "UserCreatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
            AddForeignKey("dbo.TalentProfiles", "UserUpdatedId", "dbo.AspNetUsers", "Id", cascadeDelete: false);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.TalentProfiles", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.TalentProfiles", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.TalentProfiles", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Applications", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Applications", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Jobs", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Jobs", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.JobTimeStamps", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.JobTimeStamps", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.JobTimeStamps", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Clicks", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Clicks", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Clicks", "ClickerId", "dbo.AspNetUsers");
            DropForeignKey("dbo.UserSkills", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.SavedJobs", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.SavedJobs", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.SavedJobs", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Resumes", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Resumes", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Resumes", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Jobs", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Notes", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Notes", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Notes", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Messages", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Companies", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Companies", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Messages", "UserUpdatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Messages", "UserCreatedId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Companies", "CompanyAdminId", "dbo.AspNetUsers");
            DropForeignKey("dbo.Applications", "UserId", "dbo.AspNetUsers");
            DropIndex("dbo.TalentProfiles", new[] { "UserUpdatedId" });
            DropIndex("dbo.TalentProfiles", new[] { "UserCreatedId" });
            DropIndex("dbo.TalentProfiles", new[] { "UserId" });
            DropIndex("dbo.Applications", new[] { "UserUpdatedId" });
            DropIndex("dbo.Applications", new[] { "UserCreatedId" });
            DropIndex("dbo.Jobs", new[] { "UserUpdatedId" });
            DropIndex("dbo.Jobs", new[] { "UserCreatedId" });
            DropIndex("dbo.JobTimeStamps", new[] { "UserUpdatedId" });
            DropIndex("dbo.JobTimeStamps", new[] { "UserCreatedId" });
            DropIndex("dbo.JobTimeStamps", new[] { "UserId" });
            DropIndex("dbo.Clicks", new[] { "UserUpdatedId" });
            DropIndex("dbo.Clicks", new[] { "UserCreatedId" });
            DropIndex("dbo.Clicks", new[] { "ClickerId" });
            DropIndex("dbo.UserSkills", new[] { "UserId" });
            DropIndex("dbo.SavedJobs", new[] { "UserId" });
            DropIndex("dbo.SavedJobs", new[] { "UserUpdatedId" });
            DropIndex("dbo.SavedJobs", new[] { "UserCreatedId" });
            DropIndex("dbo.Resumes", new[] { "UserId" });
            DropIndex("dbo.Resumes", new[] { "UserUpdatedId" });
            DropIndex("dbo.Resumes", new[] { "UserCreatedId" });
            DropIndex("dbo.Jobs", new[] { "UserId" });
            DropIndex("dbo.Notes", new[] { "UserId" });
            DropIndex("dbo.Notes", new[] { "UserUpdatedId" });
            DropIndex("dbo.Notes", new[] { "UserCreatedId" });
            DropIndex("dbo.Messages", new[] { "UserId" });
            DropIndex("dbo.Companies", new[] { "UserUpdatedId" });
            DropIndex("dbo.Companies", new[] { "UserCreatedId" });
            DropIndex("dbo.Messages", new[] { "UserUpdatedId" });
            DropIndex("dbo.Messages", new[] { "UserCreatedId" });
            DropIndex("dbo.Companies", new[] { "CompanyAdminId" });
            DropIndex("dbo.Applications", new[] { "UserId" });
            AlterColumn("dbo.TalentProfiles", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.TalentProfiles", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.TalentProfiles", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.JobTimeStamps", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.JobTimeStamps", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.JobTimeStamps", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.UserSkills", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.SavedJobs", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.SavedJobs", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.SavedJobs", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Resumes", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Resumes", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Resumes", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Notes", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Notes", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Notes", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Messages", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Messages", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Messages", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Companies", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Companies", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Companies", "CompanyAdminId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Clicks", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Clicks", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Clicks", "ClickerId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Jobs", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Jobs", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Jobs", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Applications", "UserUpdatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Applications", "UserCreatedId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Applications", "UserId", c => c.String(maxLength: 128));
            CreateIndex("dbo.TalentProfiles", "UserUpdatedId");
            CreateIndex("dbo.TalentProfiles", "UserCreatedId");
            CreateIndex("dbo.TalentProfiles", "UserId");
            CreateIndex("dbo.Applications", "UserUpdatedId");
            CreateIndex("dbo.Applications", "UserCreatedId");
            CreateIndex("dbo.Jobs", "UserUpdatedId");
            CreateIndex("dbo.Jobs", "UserCreatedId");
            CreateIndex("dbo.JobTimeStamps", "UserUpdatedId");
            CreateIndex("dbo.JobTimeStamps", "UserCreatedId");
            CreateIndex("dbo.JobTimeStamps", "UserId");
            CreateIndex("dbo.Clicks", "UserUpdatedId");
            CreateIndex("dbo.Clicks", "UserCreatedId");
            CreateIndex("dbo.Clicks", "ClickerId");
            CreateIndex("dbo.UserSkills", "UserId");
            CreateIndex("dbo.SavedJobs", "UserId");
            CreateIndex("dbo.SavedJobs", "UserUpdatedId");
            CreateIndex("dbo.SavedJobs", "UserCreatedId");
            CreateIndex("dbo.Resumes", "UserId");
            CreateIndex("dbo.Resumes", "UserUpdatedId");
            CreateIndex("dbo.Resumes", "UserCreatedId");
            CreateIndex("dbo.Jobs", "UserId");
            CreateIndex("dbo.Notes", "UserId");
            CreateIndex("dbo.Notes", "UserUpdatedId");
            CreateIndex("dbo.Notes", "UserCreatedId");
            CreateIndex("dbo.Messages", "UserId");
            CreateIndex("dbo.Companies", "UserUpdatedId");
            CreateIndex("dbo.Companies", "UserCreatedId");
            CreateIndex("dbo.Messages", "UserUpdatedId");
            CreateIndex("dbo.Messages", "UserCreatedId");
            CreateIndex("dbo.Companies", "CompanyAdminId");
            CreateIndex("dbo.Applications", "UserId");
            AddForeignKey("dbo.TalentProfiles", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.TalentProfiles", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.TalentProfiles", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Applications", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Applications", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Jobs", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Jobs", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.JobTimeStamps", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.JobTimeStamps", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.JobTimeStamps", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Clicks", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Clicks", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Clicks", "ClickerId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.UserSkills", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.SavedJobs", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.SavedJobs", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.SavedJobs", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Resumes", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Resumes", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Resumes", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Jobs", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Notes", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Notes", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Notes", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Messages", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Companies", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Companies", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Messages", "UserUpdatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Messages", "UserCreatedId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Companies", "CompanyAdminId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.Applications", "UserId", "dbo.AspNetUsers", "Id");
        }
    }
}
